version: '3.7'
services:
  mysql:
    container_name: dbflute-hands-on-mysql
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 43306:3306
  git:
    container_name: dbflute-hands-on-git
    image: alpine/git
    volumes:
      - ../dbflute-hands-on:/git/dbflute-hands-on
    command: clone https://github.com/dbflute-session/dbflute-hands-on.git dbflute-hands-on
  setup-dbflute-hands-on:
    image: maven:3-jdk-8
    volumes:
      - ../dbflute-hands-on:/usr/dbflute-hands-on
      - ./setup-dbflute-hands-on/entrypoint.sh:/var/entrypoint.sh
    working_dir: /usr/dbflute-hands-on
    entrypoint: /var/entrypoint.sh
    depends_on:
      - mysql
      - git
